[project]
name = "Flask_LNbits"
description = "A Flask LNbits extension."
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "ajrlewis", email = "git@ajrlewis.com" }
]
dependencies = [
    "Flask >= 2.2.2",
]
